services:
  nginx_static:
    image: nginx
    container_name: nginx_static_${INSTANCE_NAME}
    restart: always
    ports:
      - "${INSTANCE_PORT}:80"
    volumes:
      - "./static:/usr/share/nginx/html:ro"
